const Post = require("../models/post");
var uuidv4 = require("uuid4");
const User = require("../models/user");

async function index(req, res) {
  try {
    const posts = await Post.find();
    const filteredPosts = await Post.find({ Tags: "1" });
    res.status(200).json({ success: true, response: posts, filteredPosts });
  } catch (err) {
    console.log(err);
    res.status(500).json({ success: false, response: err });
  }
}

async function create(req, res) {
  const user = await User.findById(req.body.author);
  try {
    const post = await Post.create({
      //   Author: getCurrentUser,
      //id has been generated by UUID automatically
      Author: user,
      id: uuidv4(),
      LocationName: req.body.LocationName,
      Address: req.body.address,
      Tags: req.body.tags,
      Fee: req.body.fee,
      Description: req.body.description,
    });
    res.status(200).json({ success: true, response: post });
  } catch (err) {
    console.log(err);
    res.status(500).json({ success: false, response: err });
  }
}

async function filter(req, res) {
  try {
    console.log(req.query);
    const filteredPosts = await Post.find({ Tags: "1" });
    console.log("find 1------------", filteredPosts);
    res.status(200).json({ success: true, response: filteredPosts });
  } catch (err) {
    console.log(err);
    res.status(500).json({ success: false, response: err });
  }
}

async function deletePost(req, res) {
  console.log(req.body);
  try {
    deletePost = await Post.findByIdAndDelete(req.body.p_id).exec();
    console.log(deletePost);
    let posts = await Post.find({}).exec();
    res.status(200).json(posts);
  } catch (err) {
    res.status(400).json(err);
  }
}

// async function editPost(req, res) {
//   console.log(req.body);
//   try {
//     let posts = await PostModel.findByIdAndUpdate(
//       { _id: req.body.id },
//       {
//         LocationName: req.body.LocationName,
//         Address: req.body.address,
//         Tags: req.body.tags,
//         Fee: req.body.fee,
//         Descrioption: req.body.descrioption,
//       },
//       { new: true }
//     ).exec();
//     res.status(200).json(posts);
//   } catch (err) {
//     res.status(400).json(err);
//   }
// }

module.exports = {
  index,
  create,
  filter,
  deletePost,
  // editPost,
};
